### ISSUE TITLE
[QUESTION] Session execution_options are lost after commit

### ISSUE THREAD

**Issue by viniciusandd** [Senhaji-Rhazi-Hamza/multi-tenancy-example#1] opened 2020-09-21 18:58 UTC
First, your example is great.

I would like to ask a question. I created a route in [app.py](https://github.com/viniciusandd/multi-tenancy-example/blob/master/app.py) that inserts a new order, serializes it and returns it to the requester.

It correctly inserts the record in the database, but after commit, the `execution_options` are lost and the application ends up generating errors. Do you have any idea how to solve this problem? I find it strange that this problem occurs, because the `bind attribute` is passed in the` sessionmaker`.

The error message: `sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character varying = integer`. Without the `execution_options` SQLAlchemy does not know what schema it has to deal with.

**Comment by Senhaji-Rhazi-Hamza** [comment] 2020-09-21 21:56
Hey @viniciusandd 
Thanks for your kind words, and thank you for your feedback

I reproduced the problem you exposed, but i think it solved it know, you can check by replacing the function defuse_orders by this one in app.py : 


```python
def user_orders():
     user_id = request.json.get("user_id") 
    new_user = User.get_or_create(
      name="hamza3", 
      mail='hamza@gmail.com',
      password='ovious',
      organization_id='client3')
    new_user.save()
    user = User.get_by_id(user_id)
    orders = user.get_my_priced_orders_jsonified()
    return jsonify({
      "message": "orders successfully returned",
      "results": orders
    }), 200

```

So to explain what might have happend, and what i have attempted to solve it

I think when a commit is done, the session state get reinitialized, so instead of setting a state session within a
middleware (before_request) into the object session itself, we set to the BaseModel a method 'get_organization_id' that is used each time we try to query a model to generate a new session, and setup the right execution option (by modifying the getter 'cls.session') 'get_organization_id' returns the organization_id corresponding to the current request

Notice that we used a Local Proxy to ensure that we have one organization_id per request per thread

Also we have know a scoped session, basically it's always the same session per the same thread that is returned back when we generate a session : 
https://docs.sqlalchemy.org/en/13/orm/contextual.html

Let's me know if it's fine for you ! 

Here is a loom record for the test : https://www.loom.com/share/6f9fc6b98b194d2383d656d3e2c5773d

**Comment by viniciusandd** [comment] 2020-09-22 04:01
@Senhaji-Rhazi-Hamza, i thank you very much for making your time available for questioning.

I'm sorry I didn't realize that a file was missing for the project's fork to work: `ModuleNotFoundError: No module named 'lib.serealizer'`.

Your example worked very well!

```python
@app.route('/orders', methods=["POST"])
def user_orders():
	user_id = request.json.get("user_id")
	new_user = User.get_or_create(
		name="hamza3",
		mail='hamza@gmail.com',
		password='ovious',
		organization_id='client3')
	new_user.save()
	user = User.get_by_id(user_id)
	orders = user.get_my_priced_orders_jsonified()
	return jsonify({
		"message": "orders successfully returned",
		"results": orders
	}), 200
```

I noticed that the get_or_create method inserts the user successfully and after the save is called, no exception is thrown. But I still can't access the object, for example:

```
       ...
	new_user = User.get_or_create(
		name="hamza3",
		mail='hamza@gmail.com',
		password='ovious',
		organization_id='client3')
	print(new_user.id) <-- here
       ...
```

I would like to thank you again, as your mention of the `scoped_session` was very valuable.

Forgive me if I missed an explanation, I usually use `flask_sqlalchemy` and it abstracts a lot of what is done, a lot of what is in your example is new to me.

**Comment by Senhaji-Rhazi-Hamza** [comment] 2020-09-22 11:41
Hey @viniciusandd, Thanks again, and it's my pleasure,

The problem is fixed, it was due to after deleting/saving i was closing the session which has the effect of unbounding the models from session, [ref](https://docs.sqlalchemy.org/en/13/orm/session_basics.html#closing)

Hahah i had previously some thread troubles before needing to dig and un understand the need of scoped session, but as it's like extra dependency i preferred to not use it anymore

Here is a [loom video](https://www.loom.com/share/e62447bc4ba84bce87ee055d3e0608e0) that test the example you provided

Let's me know if it's fine !

**Comment by viniciusandd** [comment] 2020-09-22 12:38
@Senhaji-Rhazi-Hamza, it worked really well!

Let me thank you again, all of your examples and explanations were very valuable. I'm sure this example will help many people.

**Comment by Senhaji-Rhazi-Hamza** [comment] 2020-09-22 18:52
@viniciusandd my big pleasure ! 

So happy to know that this work is or might be useful for others ! and thanks for your 
feedback that allowed me to improve it !

Cheers !

**Closed as completed** 2020-09-22 18:53 UTC
